# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# - task: AzureResourceManagerTemplateDeployment@3
#   inputs:
#     deploymentScope: 'Resource Group'
#     azureResourceManagerConnection: 'AzureRmPipeline-conn'
#     subscriptionId: 'e043da6d-062b-4f71-a88b-a52765a0ec9a'
#     action: 'Create Or Update Resource Group'
#     resourceGroupName: 'arm-vscode'
#     location: 'Australia East'
#     templateLocation: 'URL of the file'
#     csmFileLink: 'https://raw.githubusercontent.com/alexfrq/arm-vscode/master/vs_code_linked_template/azuredeploy.json'
#     overrideParameters: '-storageAccountNamePrefix tst'
#     deploymentMode: 'Incremental'
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'AzureRmPipeline-conn'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az role assignment create --role "Storage Blob Data Contributor" --assignee admin1@alexfrqgmail.onmicrosoft.com --scope "/subscriptions/e043da6d-062b-4f71-a88b-a52765a0ec9a/resourceGroups/arm-vscode/providers/Microsoft.Storage/storageAccounts/devipxs5yzo4rp42"'
    # inlineScript: 'az account show'
    
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    # inlineScript: 'az account show'
    inlineScript: 'az role assignment create --role "Storage Blob Data Contributor" --assignee admin1@alexfrqgmail.onmicrosoft.com --scope "/subscriptions/e043da6d-062b-4f71-a88b-a52765a0ec9a/resourceGroups/arm-vscode/providers/Microsoft.Storage/storageAccounts/devipxs5yzo4rp42"'
    addSpnToEnvironment: true
    
